name: phantomjs
version: 1.0.1
summary: Full web stack. No browser required.
description: >
  "PhantomJS is a headless WebKit scriptable with a JavaScript API. It
  has fast and native support for various web standards: DOM handling,
  CSS selector, JSON, Canvas, and SVG."
confinement: devmode
apps:
  phantomjs:
    command: run
parts:
  phantomjs:
    plugin: copy
    source: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    files:
      "*": .
    stage-packages:
      - fontconfig-config
  run:
    plugin: copy
    files:
      run: bin/.
