name: phantomjs
version: 1.0.0
summary: Full web stack. No browser required.
description: >
  "PhantomJS is a headless WebKit scriptable with a JavaScript API. It
  has fast and native support for various web standards: DOM handling,
  CSS selector, JSON, Canvas, and SVG."
confinement: devmode
apps:
  phantomjs:
    command: run
parts:
  run:
    plugin: copy
    files:
      run: bin/.
      phantomjs: bin/.
    stage-packages:
      - fontconfig-config
